:source-highlighter: coderay
:source-language: clojure
:toc:
:toc-placement: preamble
:sectlinks:
:sectanchors:
:sectnums:

= EQL

image:https://img.shields.io/clojars/v/edn-query-language/eql.svg[link=https://clojars.org/edn-query-language/eql]
image:https://cljdoc.xyz/badge/edn-query-language/eql[link=https://cljdoc.xyz/d/edn-query-language/eql/CURRENT]
image:https://circleci.com/gh/edn-query-language/eql/tree/master.svg?style=svg["CircleCI", link="https://circleci.com/gh/edn-query-language/eql/tree/master"]

This repository contains a specification for EQL and a support library to help the development
of tools using it.

== What is EQL?

EQL is a declarative way to make hierarchical (and possibly nested) selections of information about data requirements.

EQL doesn't have it's own syntax, it uses EDN to express the request, taking advantage of
the rich set of primitives provided by it.

==== EQL for selections

An easy way to get started is to think of a nested map and try to describe it's shape. For example:

[source,clojure]
----
{:album/name "Magical Mystery Tour"
 :album/year 1967}
----

By describing the shape we mean describing the structure but without the values, the previous
example can be described using EQL as:

[source,clojure]
----
[:album/name :album/year]
----

Like using `select-keys` to specify which fields to extract from a map. Now let's see
what it looks like for nested structures:

[source,clojure]
----
{:album/name   "Magical Mystery Tour"
 :album/artist {:artist/name "The Beatles"}}

; can be described as:

[:album/name
 ; note the use of a map to express nesting
 {:album/artist
  [:artist/name]}]
----

It works the same to represent nested lists:

[source,clojure]
----
{:album/name   "Magical Mystery Tour"
 :album/tracks [{:track/name "The Fool On The Hill"}
                {:track/name "All You Need Is Love"}]}

; can be described as:

[:album/name
 {:album/tracks
  [:track/name]}]
----

==== EQL for operations

EQL also supports `mutations`, which are like side effect calls to an API. Mutations can
appear at the root of some EQL transaction and they look like Clojure function calls, example:

[source,clojure]
----
[(call-mutation {:data "value"})]
----

More details in <<Mutations>>.

=== Datomic Pull Syntax comparison

On top of the Datomic Pull Syntax expression, EQL also supports:

- Parametrization
- <<Mutations>>
- <<Unions,Union Queries>>

Check the links on each for more details.

The link:https://docs.datomic.com/on-prem/pull.html#attribute-with-options[attribute with options] feature
from the Datomic Pull Syntax is not present in EQL, instead we provide the parameterized
attributes that can handle arbitrary data to go along the base property.

=== GraphQL comparison

Similar to GraphQL, EQL works as a language to client libraries to communicate data requirements and operations,
there is a good set of intersection in features between both, as:

- a language to describe arbirtrarly nested structures
- support for mutations (operations to side effect the world)
- support for parametrization
- union queries for heterogeneos lists

GraphQL has a type system in its definition and it is required for a GraphQL system to work. EQL has
no such thing, and it dictates only the syntax but not the semantics. Some features in
GraphQL just doesn't make sense in EQL, like fragments, since EQL is already a data format (EDN),
it's easy to compose data as you would do in a regular Clojure program, for that reason
many features are not nescessary because EQL is a parseable data format with all the Clojure
tools already available to operate on top of it. Also read the <<AST,AST Encode/Decode>> section for more information
on how to programatically manipulate EQL data structures.

== Specification

The following sections will explain the features provided by the EQL syntax and the
common usages of it. Along with code examples from the transactions, after that we
are going to provide the AST data that's equivalent to the transaction, the AST the
recommended format to transform EQL transactions programatically. The EQL format is
great for users and interfaces, but to transform is easier if you don't have to deal
with the syntax details. The EQL library provides functions to convert from and to
AST from EQL.

=== Query / Transactions

A EQL transaction is represented by an EDN vector.

Examples:

[source,clojure]
----
[] # empty transaction
----

[source,clojure]
----
{:type :root, :children []}
----

A transaction that only contains reads is commonly called a `query`, but notice that
at syntax level it has no difference.

=== Properties

Properties in `EQL` are expressed as Clojure keywords, they can be simple or qualified
keywords, and they express the property been requested.

For example,

=== Joins

Joins are used to describe nesting in the request transaction. They are represented as
EDN maps, always with a single entry, the entry key is the property to join on, and the
entry value is a sub-query to run.

Examples:

[source,clojure]
----
[{:favorite-albums
  [:album/name :album/year]}]
----

=== Idents

Idents are represented by a vector with two elements, where the first is a keyword and
the second can be anything. They are like link:http://blog.datomic.com/2014/02/datomic-lookup-refs.html[lookup refs on Datomic],
in general they can provide an address-like thing, and their use and semantic might
vary from system to system.

Examples:

[source,clojure]
----
[[:customer/id 123]]
----

=== Parameters

=== Unions

=== Mutations

== Library

=== Clojure Specs

=== AST Encode/Decode

//== History
//
//EQL is a later baptized language, it's initial syntax was defined by link:https://docs.datomic.com/pull.html[Datomic Pull Syntax], later extended
//by link:https://github.com/omcljs/om[Om.next].

//== Projects using EQL
//
//- link:http://fulcro.fulcrologic.com/[Fulcro]
//- link:https://github.com/wilkerlucio/pathom[Pathom]
//- link:https://github.com/walkable-server/walkable[Walkable]
